apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-policies
  namespace: company-rhacs
spec:
  # every 2 hours on xx:21, monday-friday
  schedule: "21 */2 * * 1-5"
  #timeZone: Europe/Berlin       # may be supported after k8s v1.24
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/company-rhacs/roxctl:latest
              name: load-policies
              env:
# NB: CLUSTERNAME env is added by cluster-specific kustomize patch
              - name: PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: central-htpasswd
                    key: password
              - name: NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              command:
                - /bin/bash
                - /scripts/load-policies.sh
              imagePullPolicy: Always
              volumeMounts:
              - mountPath: /scripts
                name: scripts
                readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          serviceAccountName: rhacs-sync-job-user
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: scripts
            name: scripts
