apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: rhacs-syncpolicies
  namespace: company-rhacs
rules:
  # allow to use initial passwd to connect to rhacs API
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - "*"
