apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: postinstall-rhacs-jobs
  namespace: company-rhacs
rules:
  # allow to use initial passwd to connect to rhacs API
  - apiGroups:
    - ""
    resourceNames:
    - central-htpasswd
    resources:
    - secrets
    verbs:
    - get
# update secret containing newly generated rhacs API token
  - apiGroups:
    - ""
    resourceNames:
    - gitops-api-token
    - collector-tls
    - sensor-tls
    - admission-control-tls
    resources:
    - secrets
    verbs:
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - route.openshift.io
    resources:
    - routes
    verbs:
    - get
    - list
    - watch
